# openapi2-functions.yaml
swagger: '2.0'
info:
  title: Petshop cart API
  description: Clientside shopping cart API for petshop
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /item:
    post:
      summary: add to cart
      operationId: additem
      x-google-backend:
        address: us-central1-week10-1-324606.cloudfunctions.net/function-name
      consumes:
        - application/json
      parameters:
        - in: body
          name: item
          description: The item to add.
          schema:
            type: object
            properties:
              id:
                type: integer
                default: 0
              user_id:
                type: integer
                default: 0
              product_id:
                type: integer
                default: 0
              amount:
                type: integer
                default: 1
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    delete:
      summary: remove from cart
      operationId: deleteitem
      x-google-backend:
        address: us-central1-week10-1-324606.cloudfunctions.net/function-name
      consumes:
        - application/json
      parameters:
        - in: body
          name: item
          description: The item to delete.
          schema:
            type: object
            properties:
              id:
                type: integer
                default: 0
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    put:
      summary: update item in cart
      operationId: updateitem
      x-google-backend:
        address: us-central1-week10-1-324606.cloudfunctions.net/function-name
      consumes:
        - application/json
      parameters:
        - in: body
          name: item
          description: The item to update.
          schema:
            type: object
            properties:
              id:
                type: integer
                default: 0
              user_id:
                type: integer
                default: 0
              product_id:
                type: integer
                default: 0
              amount:
                type: integer
                default: 1
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /item/{id}:  
    get:
      tags:
      - item
      summary: get item by id
      description: returns a single item
      operationId: itempbyid
      x-google-backend:
          address: us-central1-week10-1-324606.cloudfunctions.net/function-name
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of item to return
        required: true
        type: integer
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              id:
                type: integer
                default: 0
              user_id:
                type: integer
                default: 0
              product_id:
                type: integer
                default: 0
              amount:
                type: integer
                default: 0
        400:
          description: Invalid ID supplied
        404:
          description: Item not found